/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codenine.vista;

import codenine.dto.AsistenciaDTO;
import codenine.dto.OcurrenciaDto;
import codenine.dto.OficinaDTO;
import codenine.interfaz.AsistenciaInterfaz;
import codenine.interfaz.OficinaInterfaz;
import codenine.modelo.AsistenciaImpl;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import codenine.modelo.OficinaImpl;
import codenine.modelo.VistaMensajes;

/**
 *
 * @author Francisco Ninus
 */
public final class Principal extends javax.swing.JFrame {

    JComboBox comboBox = new JComboBox();
    OficinaDTO cmbo = new OficinaDTO();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        VistaMensajes.mensaje();
        CargarTablaIndex();
        CargarComboBox();
        CargarComboBoxOficina();
        txtFecha.setEnabled(false);
        setLocationRelativeTo(null);

    }

    void CargarComboBox() {

        AsistenciaInterfaz proc = new AsistenciaImpl();
        comboBox.setModel(proc.combo());
        //se agrega model al JTable
        tbAsistencia.setRowHeight(22);//altura de filas
        //se indica que columna tendra el JComboBox
        tbAsistencia.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboBox));
        tbAsistencia.setDefaultRenderer(Object.class, new CeldaRenderer(6));
    }

    void CargarComboBoxOficina() {
        OficinaInterfaz proc = new OficinaImpl();
        cmbOficina.setModel(proc.combo());
    }

    void CargarTabla(OficinaDTO cmbo) {
        AsistenciaInterfaz proc = new AsistenciaImpl();
        tbAsistencia.setModel(proc.tablaAsistencia(cmbo));
        tbAsistencia.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbAsistencia.getColumnModel().getColumn(1).setPreferredWidth(20);
        tbAsistencia.getColumnModel().getColumn(2).setPreferredWidth(20);
        tbAsistencia.getColumnModel().getColumn(3).setPreferredWidth(20);
        tbAsistencia.getColumnModel().getColumn(4).setPreferredWidth(10);
        tbAsistencia.getColumnModel().getColumn(5).setPreferredWidth(40);
        tbAsistencia.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboBox));
        tbAsistencia.getColumnModel().getColumn(7).setPreferredWidth(100);
//        tbAsistencia.setDefaultRenderer(Object.class, new CeldaRenderer(4));
    }

    void CargarTablaIndex() {
        AsistenciaInterfaz proc = new AsistenciaImpl();
        tbAsistencia.setModel(proc.tabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAsistencia = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbOficina = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Nombre", "Opciones", "Detalles"
            }
        ));
        jScrollPane1.setViewportView(tbAsistencia);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardarN.png"))); // NOI18N
        btnAgregar.setText("REGISTRAR ASISTENCIA");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("OFICINA:");

        cmbOficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CONTROL DE ASISTENCIA DEL PERSONAL");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gerencia.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_1.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbOficina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(312, 312, 312))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActualizar)
                                .addGap(21, 21, 21)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cmbOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel4))))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnActualizar))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        OficinaDTO cmbo = (OficinaDTO) cmbOficina.getSelectedItem();
        CargarTabla(cmbo);
        txtFecha.setEnabled(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

       AsistenciaInterfaz proc = new AsistenciaImpl();
        AsistenciaDTO dto = new AsistenciaDTO();
        Date date = txtFecha.getDate();

        if (date == null) {
            JOptionPane.showMessageDialog(null, "Debe Colocar Fecha");
        } else {

            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = null;
            fecha = format1.format(date);
//
//            int rowsInsert = 0;
            for (int i = 0; i < tbAsistencia.getRowCount(); i++) {
                Object f = tbAsistencia.getModel().getValueAt(i, 1);
                Object g = tbAsistencia.getModel().getValueAt(i, 2);
                dto.setNombre(f + " " + g);

                OcurrenciaDto c6 = (OcurrenciaDto) tbAsistencia.getValueAt(i, 6);
//              
                if (c6 == null) {
                    JOptionPane.showMessageDialog(null, "Seleccione una ocurrencia");
                } else {
                    int c0 = (int) tbAsistencia.getValueAt(i, 0);
                    String c7 = (String) tbAsistencia.getValueAt(i, 7);
                    dto.setIdpersona(c0);
                    dto.setFecha(fecha);
                    dto.setOcurrencia(String.valueOf(c6.getIdOcurrencia()));
                    dto.setDetalle(c7);

                    proc.registrar(dto);
                }
                System.out.println("vuelta: " + i + " - " + dto.getIdpersona() + " " + dto.getFecha());
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

       AsistenciaInterfaz proc = new AsistenciaImpl();
        AsistenciaDTO dto = new AsistenciaDTO();
        Date date = txtFecha.getDate();

        if (date == null) {
            JOptionPane.showMessageDialog(null, "Debe Colocar Fecha");
        } else {

            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = null;
            fecha = format1.format(date);

            
            for (int i = 0; i < tbAsistencia.getRowCount(); i++) {
                Object f = tbAsistencia.getModel().getValueAt(i, 1);
                Object g = tbAsistencia.getModel().getValueAt(i, 2);
                dto.setNombre(f + " " + g);
                OcurrenciaDto c6 = (OcurrenciaDto) tbAsistencia.getValueAt(i, 6);
//              
                if (c6 == null) {
                    JOptionPane.showMessageDialog(null, "Seleccione una ocurrencia");
                } else {
                    int c0 = (int) tbAsistencia.getValueAt(i, 0);
                    String c7 = (String) tbAsistencia.getValueAt(i, 7);
                    
                    dto.setIdpersona(c0);
                    dto.setFecha(fecha);
                    dto.setOcurrencia(c6.getDescripcion());
                    dto.setDetalle(c7);

                    proc.actualizar(dto);
                }
                System.out.println("vuelta: " + i + f);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       AsistenciaInterfaz proc = new AsistenciaImpl();
        AsistenciaDTO dto = new AsistenciaDTO();
        Date date = txtFecha.getDate();

        if (date == null) {
            JOptionPane.showMessageDialog(null, "Debe Colocar Fecha");
        } else {

            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = null;
            fecha = format1.format(date);

            for (int i = 0; i < tbAsistencia.getRowCount(); i++) {
                Object f = tbAsistencia.getModel().getValueAt(i, 1);
                Object g = tbAsistencia.getModel().getValueAt(i, 2);
                dto.setNombre(f + " " + g);
                OcurrenciaDto c6 = (OcurrenciaDto) tbAsistencia.getValueAt(i, 6);
//              
               
                    int c0 = (int) tbAsistencia.getValueAt(i, 0);
                    dto.setIdpersona(c0);
                    dto.setFecha(fecha);

                    proc.eliminar(dto);
                
                System.out.println("vuelta: " + i + f);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbOficina;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAsistencia;
    private com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
